version: "3"

services:

   ap-it:
    image: packit/ap-it:latest
    restart: always
    container_name: ap-it
    depends_on:
        - mssql-server
        - mongodb-server
    ports:      
        - "3000:3000"
    networks:
        - packit
    command: ["./wait-for-it.sh", "mssql-server:1433", "-t", "15", "--", "pnpm", "start"]

   mssql-server:
    image: packit/mssql-server:latest
    restart: always
    container_name: mssql-server
    ports: 
        - "1433:1433"
    networks:
        - packit

   mongodb-server:
    image: packit/nosql-server:latest
    restart: always
    container_name: mongodb-server
    ports:
        - "27017:27017"
    networks:
        - packit

networks:
    packit:

    
