version: "3"

services:

   ap-it:
    image: packit/ap-it:latest
    restart: always
    container_name: ap-it
    ports:      
        - "3000:3000"
    networks:
        - pack-it-network

   mssql-server:
    image: packit/mssql-server:latest
    restart: always
    container_name: mssql-server
    ports: 
        - "1433:1433"
    networks:
        - pack-it-network

   mongodb-server:
    image: packit/nosql-server:latest
    restart: always
    container_name: mongodb-server
    ports:
        - "27017:27017"
    networks:
        - pack-it-network

networks:
    pack-it-network:
