version: "3"

services:

   ap-it:
    image: packit/ap-it:latest
    restart: always
    container_name: ap-it
    depends_on:
        - mssql-server
        - mongodb-server
    ports:      
        - "3000:3000"
    network_mode: host
    command: ["./wait-for-it.sh", "db:1433", "-t", "5", "--", "pnpm", "start"]

   mssql-server:
    image: packit/mssql-server:latest
    restart: always
    container_name: mssql-server
    ports: 
        - "1433:1433"
    network_mode: host

   mongodb-server:
    image: packit/nosql-server:latest
    restart: always
    container_name: mongodb-server
    ports:
        - "27017:27017"
    network_mode: host

    
