version: "3"

services:

   ap-it:
    image: packit/ap-it:latest
    restart: always
    pull: true
    container_name: ap-it
    ports:      
        - "3000:3000"
    networks:
      pack-it-network:
        aliases:
         - ap-it
  
networks:
    pack-it-network:
